config/routes.rb
Rails.application.routes.draw do

  root "static#home"
  match '/standings', to: "static#standings", via: 'get'
  match '/tournaments', to: "static#tournaments", via: 'get'
  match '/highlights', to: "static#highlights", via: 'get'
  match '/charities', to: "static#charities", via: 'get'
  match '/about', to: "static#about", via: 'get'
  match '/contact', to: "static#contact", via: 'get'
  match '/schedules', to: "static#schedules", via: 'get'
  match '/rules', to: "static#rules", via: "get"

  resources :tournaments do
    resources :contestants
    end

  

end

app/models/contestant.rb
class Contestant < ActiveRecord::Base
	belongs_to :tournament
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
	has_many :contestants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contestants_controller.rb
class ContestantsController < ApplicationController
	def create
		@tournament = Tournament.find(params[:tournament_id])
		@contestant = @tournament.contestants.create(contestant_params)
		redirect_to tournament_path(@tournament)
	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def standings
  end

  def tournaments
  end

  def highlights
  end

  def charities
  end

  def about
  end

  def contact
  end

  def schedules
  end

  def rules
  end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
	def new
		@tournament = Tournament.new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contestants_helper.rb
module ContestantsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/layouts/_footer.html.erb
<div id="mainfooter">
	<div id="content">
		<nav id="headernav">
		</nav>
	</div>
</div>

app/views/layouts/_header.html.erb
<div id="mainheader">
	<div id="content">
		<nav id="socialmedia">
			<a href="https://www.facebook.com" ><img class="hicon" src="facebook.png"></a>
			<a href="https://www.twitter.com" ><img class="hicon" src="twitter.png"></a>
			<a href="https://www.youtube.com"><img class="hicon" src="youtube.png"></a>
			<a href="/"><img class="hicon" src="search.png"></a>
		</nav>
		<nav id="headernav">
			<%= link_to 'Charities', charities_path %>
			<%= link_to 'Sponsors', charities_path %>
			<%= link_to 'About', about_path %>
			<%= link_to 'Contact', contact_path, :style => "border-right: none;" %>
		</nav>
	</div>
</div>


	<div id="secondheaderbox">
	<div id="content">
		<div id="headlogobox">
		<span id="mainlogo">
			<a href="/">Best<span id="headchamp">Champion</span>NA</a>
			<!--<img class="hlogo" src="/mainlogo.jpg">!-->
		</span>
		</div>

	<nav id="secondheadernav">
			<%= link_to 'Schedule', schedules_path %>
			<%= link_to 'Tournaments', tournaments_path %>
			<%= link_to 'Rules', rules_path %>
			<%= link_to 'Standings', standings_path %>
			<%= link_to 'Highlights', highlights_path %>
	</nav>
	</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leagueoflegendscharity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="wrapper">
		
		<%= render 'layouts/header' %>
			<div id="indenttopbot">
					<%= yield %>
			</div>
		
	</div>
	<%= render 'layouts/footer' %>
	
</body>
</html>